### ISSUE TITLE
Slow build time for gl::load_with usages

### ISSUE THREAD

**Issue by ntrrgc** [brendanzab/gl-rs#313] opened 2015-02-20 17:45 UTC
On my i5-3550 this code takes 3.2 seconds to build, which is quite a bit taking into account it is only loading the OpenGL library.

```
extern crate glutin;
extern crate gl;

fn main() {
    let window = glutin::Window::new().unwrap();
    unsafe { window.make_current() };
    gl::load_with(|symbol| window.get_proc_address(symbol));
}
```

It was tested with rustc 1.0.0-nightly (dfc5c0f1e 2015-02-18).

**Comment by jonas-schievink** [comment] 2016-07-02 11:24
#406 should have made this somewhat faster, but the main problem seems to be that `load_with` is generic and is thus inlined into the using crate instead of being simply linked against (like `#[inline]` functions). Can probably be fixed by making `load_with` take a `&FnMut`.

**Comment by winduptoy** [comment] 2018-10-14 22:56
@jonas-schievink thanks. Any tips on how I might go about doing that? I'm afraid I don't understand the alternative methods available in this Rust setup.

For comparison, a simple `glutin` + `gl` window is compiling in 1 minute and 8 seconds on my Celeron laptop. Commenting out the `gl::load_with` line brings the compilation time down to 6 seconds (obviously panics at runtime).

**Comment by jonas-schievink** [comment] 2018-10-15 01:54
I'm not sure how the code generated by gl-rs looks today, but 1 minute does sound like rustc is at least partially at fault. I don't have anything more specific, sorry.

**Comment by brendanzab** [comment] 2018-10-15 03:53
Yep, we'll probably have to look at things again

**Comment by brendanzab** [comment] 2018-10-15 03:54
I'm pretty sure we removed the templates... I might not have remembered to close this issue

**Comment by mninja** [comment] 2019-01-13 16:36
This is still the case for 0.11, `gl::load_with` increases build time from 2 to 15 seconds compared to loading pointers individually.

**Comment by LukasKalbertodt** [comment] 2019-07-04 18:13
This is still a problem for me. Even with incremental compilation, using `load_with` adds several seconds to the build time. 

I'm not sure what the problem is now, but it looks like `gl::load_with` still calls roughly 700 other `load_with` functions from submodules. The submodule's `load_with` still have the closure as generic type and not as `&mut dyn FnMut`. They are also not marked with `#[inline(never)]`. I'd bet that changing these two things would improve things a lot. What do you think?

**Comment by brendanzab** [comment] 2019-07-04 23:29
Ah yes, that seems like the culprit!

**Comment by LukasKalbertodt** [comment] 2019-07-04 23:36
Now that I think about it, I would probably *also* create an inner function inside `gl::load_with` which takes `&mut dyn FnMut` and is also marked with `#[inline(never)]`. The outer `gl::load_with` would then only call the inner one. That way, the 700 calls are not inlined into user code. 

I could submit this as PR, if you want. Or do you want to do it?

**Comment by brendanzab** [comment] 2019-07-04 23:38
I'd definitely accept a PR! I'm not doing much graphics work at the moment, so I'm kind of relying on contributions at this stage.

**Comment by LukasKalbertodt** [comment] 2019-07-09 08:30
@brendanzab Do you think the improvements from #495 are good enough to justify closing this issue? At least for now? And/or do you want to wait until the patch is released to crates.io? Are you planning to release this in a point release or with "0.13.0"?

**Comment by brendanzab** [comment] 2019-07-09 12:28
Thanks for the reminder! I'm also getting asked here: #494. I'm guessing this is a breaking change (even with the pinned travis version), so I'll ratchet up a new minor version.

**Closed** 2019-07-09 13:00 UTC

**Comment by brendanzab** [comment] 2019-07-09 13:01
Published!
